#!/bin/sh

# PROVIDE: renderd
# REQUIRE: LOGIN postgresql
# KEYWORD: shutdown

. /etc/rc.subr

PATH=$PATH:/usr/local/bin:/usr/local/sbin

name="renderd"
rcvar=${name}_enable

load_rc_config ${name}

start_cmd="sudo -u _renderd renderd -c /usr/local/etc/renderd/renderd.conf $*"
stop_cmd="kill -9 `cat /var/run/renderd/renderd.pid`"
restart_cmd="kill -9 `cat /var/run/renderd/renderd.pid`; sudo -u _renderd renderd -c /usr/local/etc/renderd/renderd.conf $*"

run_rc_command "$1"
