#!/bin/sh

# PROVIDE: renderd
# REQUIRE: LOGIN postgresql
# BEFORE:  securelevel
# KEYWORD: shutdown

# Add the following lines to /etc/rc.conf to enable `ceph':
#
# renderd_enable="YES"
#

. /etc/rc.subr

PATH=$PATH:/usr/local/bin:/usr/local/sbin

name="renderd"
rcvar=${name}_enable
#extra_commands="condrestart"

load_rc_config ${name}

# read configuration and set defaults
: ${ceph_enable="NO"}
: ${ceph_configfile:=/usr/local/etc/ceph/ceph.conf}

start_cmd="sudo -u _renderd renderd -c /usr/local/etc/renderd/renderd.conf $*"
stop_cmd="kill -9 `cat /var/run/renderd/renderd.pid`"
restart_cmd="kill -9 `cat /var/run/renderd/renderd.pid`; sudo -u _renderd renderd -c /usr/local/etc/renderd/renderd.conf $*"
#condrestart_cmd="/usr/local/bin/init-ceph $*"

run_rc_command "$1"

